apiVersion: apps/v1
kind: Deployment
metadata:
  name: timekeeper-web-deployment  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: timekeeper-web-deployment
  template:
    metadata:
      labels:
        app: timekeeper-web-deployment
    spec:
      containers:
      - name: timekeeper-web-deployment
        image: andrew86haine/timekeeper:latest
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: timekeeper-web-service 
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8000
  selector:
    app: timekeeper-web-deployment
    
  

  