apiVersion: apps/v1
kind: Deployment
metadata:
  name: timekeeper-web  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: timekeeper-web
  template:
    metadata:
      labels:
        app: timekeeper-web
    spec:
      containers:
      - name: timekeeper-web
        image: andrew86haine/timekeeper:latest
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: timekeeper-web  
spec:
  type: ClusterIP
  selector:
    app: timekeeper-web
  ports:
    - port: 80
      targetPort: 8000
    
  

  