apiVersion: apps/v1
kind: Deployment
metadata:
  name: timekeeper-web  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: timekeeper-web
  template:
    metadata:
      labels:
        app: timekeeper-web
    spec:
      containers:
      - name: timekeeper-web
        image: andrew86haine/timekeeper:latest
        ports:
        - containerPort: 80
        # env:
        # - name: TITLE
        #   value: "Welcome to Azure Kubernetes Service (AKS)"
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: timekeeper-web  
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: timekeeper-web