apiVersion: apps/v1
kind: Deployment
metadata:
  name: timekeeper-web  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: timekeeper-web
  template:
    metadata:
      labels:
        app: timekeeper-web
    spec:
      containers:
      - name: timekeeper-web
        image: andrew86haine/timekeeper:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: timekeeper-web  
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: timekeeper-web