# Generated by Django 4.1 on 2023-01-16 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timeKeeper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskBase',
            fields=[
                ('modelbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='timeKeeper.modelbase')),
            ],
            bases=('timeKeeper.modelbase',),
        ),
        migrations.CreateModel(
            name='TaskStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Task status',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('taskbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tasks.taskbase')),
                ('short_description', models.CharField(max_length=30)),
                ('full_description', models.CharField(max_length=1000)),
                ('due_date', models.DateTimeField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('task_status', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='tasks.taskstatus')),
            ],
            bases=('tasks.taskbase',),
        ),
    ]
