name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    environment: prod
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.10.6]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Show dir contents
      run: |
        ls -l
    - name: Output Run ID
      run: echo ${{ github.run_id }}
    - name: Output Run Number
      run: echo ${{ github.run_number }}
    - name: Output Run Attempt
      run: echo ${{ github.run_attempt }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r src/requirements.txt
    - shell: bash
      env:
        SUPER_SECRET: ${{ secrets.DOCKER_IO_USERNAME }}
      run: |
        echo "$SUPER_SECRET"
    - name: Docker Login
      # You may pin to the exact commit or the version.
      # uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      uses: docker/login-action@v2.1.0
      with:
        # Server address of Docker registry. If not set then will default to Docker Hub
        registry: docker.io
        # Username used to log against the Docker registry
        username: ${{ secrets.DOCKER_IO_USERNAME }}
        # Password or personal access token  used to log against the Docker registry
        password: ${{ secrets.DOCKER_IO_PASSWORD }}
        # Specifies whether the given registry is ECR (auto, true or false)
        ecr: false
        # Log out from the Docker registry at the end of a job
        logout: true
    - name: Build and push Docker images
      # You may pin to the exact commit or the version.
      # uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
      uses: docker/build-push-action@v4.0.0
      with:
        # Build's context is the set of files located in the specified PATH or URL
        context: 'src'# optional
        # Path to the Dockerfile
        file: './src/Dockerfile'# optional
        # List of metadata for an image
        labels: ''# optional
        # Do not use cache when building the image
        no-cache: false # optional, default is false
        # Always attempt to pull all referenced images
        pull: false # optional, default is false
        # Push is a shorthand for --output=type=registry
        push: true # optional, default is false
        # List of tags
        tags: 'andrew86haine/timekeeper:0.1.${{github.run_number}},andrew86haine/timekeeper:latest'# optional
#     - name: Run Tests
#       run: |
#         python src/timeKeeper/manage.py test
